version: '3'

services:
  notifications_generator:
    build:
      context: ./notifications_generator
      dockerfile: DockerFile
    image: notifications_generator:latest
    container_name: notifications_generator
    depends_on:
      - postgres
      - notifications_service
    env_file:
      - ./.env

  rabbitmq:
    env_file:
      - .env
    container_name: rabbitmq
    hostname: ${RABBITMQ__HOST}
    image: rabbitmq:3.11-management
    restart:
      always
    expose:
      - ${RABBITMQ__PORT}
      - "15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ__USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ__PASSWORD}

  postgres:
    container_name: postgres
    env_file:
      - .env
    hostname: ${POSTGRES__HOST}
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES__USER}
      - POSTGRES_PASSWORD=${POSTGRES__PASSWORD}
      - POSTGRES_DB=${POSTGRES__DBNAME}
    expose:
      - ${POSTGRES__PORT}

  admin-panel:
    container_name: admin-panel
    build: admin_panel
    env_file:
      - .env
    environment:
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
    restart:
      always
    expose:
      - ${DJANGO__PORT}

  notifications_service:
    build:
      context: ./notifications_service
      dockerfile: DockerFile
    container_name: notifications_service
    env_file:
      - .env
    hostname: ${FASTAPI__HOST}
    restart: always
    expose:
      - ${FASTAPI__PORT}
    depends_on:
      - rabbitmq

  email_server:
    build:
      context: ./email_server
      dockerfile: DockerFile
    image: email_server:latest
    container_name: email_server
    expose:
      - "25"

  clickhouse:
    image: yandex/clickhouse-server:21.7.4
    env_file:
      - .env
    container_name: clickhouse
    hostname: ${CLICKHOUSE__HOST}
    expose:
      - "8123"
      - ${CLICKHOUSE__PORT}


  worker:
    build:
      context: ./worker
      dockerfile: DockerFile
    image: worker:latest
    container_name: worker
    depends_on:
      - rabbitmq
      - clickhouse
    env_file:
      - ./.env

  notifications_handler:
    build:
      context: ./notifications_handler
      dockerfile: DockerFile
    container_name: notifications_handler
    depends_on:
      - clickhouse
      - notifications_service
    expose:
      - "8005"
    env_file:
      - ./.env
