# Generated by Django 4.1.6 on 2023-02-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usernotification",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
    ]
